#!/bin/bash -e

function increment_release {
    FILENAME=$1

    RELEASEVER=$(grep '%define release' ${FILENAME} | awk -F ' ' '{print $3}')
    if [ "${CIRCLE_BUILD_NUM}" != "" ]; then
        NEWVER=${CIRCLE_BUILD_NUM}
    else
        NEWVER=$(($RELEASEVER+1))
    fi
    echo Release version was ${RELEASEVER}, now is ${NEWVER}
    cat ${FILENAME} | sed "s/\%define release .*/%define release ${NEWVER}/" > ${FILENAME}.new
    mv ${FILENAME} ${FILENAME}.old
    mv ${FILENAME}.new ${FILENAME}
}

#from http://stackoverflow.com/questions/3915040/bash-fish-command-to-print-absolute-path-to-a-file
function abspath() {
    # generate absolute path from relative path
    # $1     : relative filename
    # return : absolute path
    if [ -d "$1" ]; then
        # dir
        (cd "$1"; pwd)
    elif [ -f "$1" ]; then
        # file
        if [[ $1 == */* ]]; then
            echo "$(cd "${1%/*}"; pwd)/${1##*/}"
        else
            echo "$(pwd)/$1"
        fi
    fi
}

BASEPATH=$(abspath "${BASH_SOURCE%/*}")

echo ----------------------------
echo Packaging RPM
echo ----------------------------

#we build the rpm from a Python source package (rpm does a setup.py install from this). So, make one and put it where RPM expects it.
#the filename we output here (the .tar.gz generated by sdist) is calculated from the package name in setup.py
#and is also specified in the Sources0: line of the RPM spec file. If you change one you must change the other!

mkdir -p ${HOME}/rpmbuild/SOURCES
cd src
python ./setup.py sdist
mv dist/*.tar.gz ${HOME}/rpmbuild/SOURCES
cd ${BASEPATH}

SPECFILE=assetsweeper.spec
increment_release assetsweeper.spec

if [ "${CIRCLE_BUILD_NUM}" == "" ]; then
    CIRCLE_BUILD_NUM=dev
fi

RPM_BASE=$(grep '%define name' ${SPECFILE} | awk -F ' ' '{print $3}')
PATH=/usr/bin:/bin:/usr/local/bin
rpmbuild -bb ${SPECFILE}

if [ "$?" != "0" ]; then
    exit $?
fi

if [ -x "/usr/bin/sha256sum" ]; then
    SHASUM="/usr/bin/sha256sum"
else
    SHASUM="/usr/bin/shasum -a 256"
fi

for x in `ls ${HOME}/rpmbuild/RPMS/noarch/${RPM_BASE}*.rpm`; do
    HASH=$(${SHASUM} "$x" | cut -d ' ' -f 1)
    echo -e "sha256=$HASH" > assetsweeper.rpm.sha
    aws s3 cp "$x" s3://gnm-multimedia-deployables/asset_folder_importer/${CIRCLE_BUILD_NUM}/`basename $x` --acl public-read
    aws s3 cp assetsweeper.rpm.sha s3://gnm-multimedia-deployables/asset_folder_importer/${CIRCLE_BUILD_NUM}/`basename $x`.sha --acl public-read
    if [ "$?" != "0" ]; then
        exit $?
    fi
done